language: node_js
node_js:
- '0.10'
- '0.12'
- stable
before_install:
  - npm install -g npm
  - npm install -g karma-cli
sudo: false
install:
- npm install -g bower
- npm install
- bower install
script:
- npm run travis
after_script:
- cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
